- name: install web component
  hosts: web
  become: yes
  tasks:
    - name: install nginx
      ansible.builtin.yum:
        name: nginx
        state: installed

    - name: test nginx configuration
      command: nginx -t
      register: nginx_config_test
      failed_when: nginx_config_test.rc != 0
      changed_when: false  # This task should not report a change

    - name: start and enable nginx
      ansible.builtin.systemd:
        name: nginx
        state: started
        enabled: yes
      when: nginx_config_test.rc == 0  # Only start nginx if config is valid

    - name: remove html directory
      ansible.builtin.file:
        path: /usr/share/nginx/html/
        state: absent

    - name: create html directory
      ansible.builtin.file:
        path: /usr/share/nginx/html/
        state: directory

    - name: download web artifact
      ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/web.zip
        dest: /tmp/web.zip

    - name: extract catalogue artifact
      ansible.builtin.unarchive:
        src: /tmp/web.zip
        dest: /usr/share/nginx/html/
        remote_src: yes

    - name: copy roboshop.conf
      ansible.builtin.copy:
        src: roboshop.conf
        dest: /etc/nginx/default.d/roboshop.conf

    - name: restart nginx
      ansible.builtin.systemd:
        name: nginx
        state: restarted
        enabled: yes
      when: nginx_config_test.rc == 0  # Only restart nginx if config is valid
